# Generated by Django 2.2.10 on 2020-04-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('os', models.CharField(max_length=10)),
                ('ram', models.PositiveIntegerField(null=True)),
                ('ppi', models.PositiveIntegerField()),
                ('double_camera', models.BooleanField()),
                ('processor', models.CharField(max_length=20)),
                ('screen_resolution', models.CharField(max_length=10)),
                ('fm_radio', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('air_pods', models.BooleanField()),
                ('face_id', models.BooleanField()),
                ('apple_pay', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Mi',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
            ],
            bases=('phones.phone',),
        ),
        migrations.CreateModel(
            name='Samsung',
            fields=[
                ('phone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phones.Phone')),
                ('double_sided_screen', models.BooleanField()),
            ],
            bases=('phones.phone',),
        ),
    ]
