# Generated by Django 2.2.10 on 2020-04-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200430_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Отношение статья-раздел', 'verbose_name_plural': 'Отношения статья-раздел'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
