# Generated by Django 2.2.10 on 2020-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200430_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(related_name='scopes', through='articles.Relationship', to='articles.Article'),
        ),
    ]
