# Generated by Django 2.2.10 on 2020-04-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200430_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='topic',
            new_name='scope',
        ),
    ]
