# Generated by Django 2.2.10 on 2020-05-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
    ]
