# Generated by Django 2.2.10 on 2020-05-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='C:\\Projects\\DjangoProjects\\dj-homeworks\\site-personalization\\paid_content\\images'),
        ),
    ]
