# Generated by Django 2.2.10 on 2020-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playergameinfo',
            name='attempts_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
