# Generated by Django 2.2.10 on 2020-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200514_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
